# -*- coding: utf-8 -*-
"""Copy of Hands_On_Function_in_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H1WL9--S2Eq7IKUf7c2Cj-tF_FyPSjMv

**Format dasar function:**
"""

def nama_function():
    print("Hello, ini function pertamaku")

#Untuk menjalankan function, cukup panggil namanya
nama_function()

"""**Function dengan Parameter**

Parameter ditentukan setelah nama fungsi, di dalam tanda kurung. Kita dapat menambahkan perintah sebanyak yang kita inginkan, cukup pisahkan dengan koma.
"""

def panggil (nama):
    print(f"Halo, {nama}! Ada yang bisa dibantu?")

panggil("Rayhan")

"""**Hands On**

Jika saya ingin membuat nama "***Felda Ramadhan***"
Bagaimana cara untuk melengkapi program dibawah ini ???
"""

def panggil(nama):
    print("Halo, " + nama + "!")

panggil("Felda Ramadhan")

"""**Function dengan Default Parameter**

Kita juga bisa memberikan nilai default pada parameter
"""

def panggil(nama="User"):
    print(f"Halo, {nama}")

panggil()
panggil("Raihan Noval")

"""* Fungsi sapa memiliki satu parameter bernama "nama", yang memiliki nilai default "User".
* print(f"Halo, {nama}") digunakan untuk mencetak teks "Halo, {nama}" dengan nilai nama yang diberikan.

**Function dengan Return Value**

Function bisa mengembalikan nilai dengan *return*
"""

def tambah(a, b):
    return a + b

hasil = tambah(5, 3)
print(hasil)

"""Penjelasan:

*return* diatas bertugas untuk mengembalikan hasilnya ke pemanggil

Kita mendefinisikan fungsi bernama tambah yang menerima dua parameter, a dan b.
* return a + b: Mengembalikan hasil penjumlahan dari a dan b.
* Fungsi tambah(5, 3) dipanggil dengan nilai a = 5 dan b = 3.
* Fungsi tambah mengembalikan hasil 5 + 3 = 8, yang kemudian disimpan dalam variabel hasil.

**Function dengan Banyak Parameter (Arbitrary Arguments)**

Jika jumlah parameter tidak diketahui, kita bisa gunakan *args atau ***kwargs
"""

# *args untuk banyak argumen tanpa nama
def jumlahkan(*angka):
    return sum(angka)

print(jumlahkan(1, 2, 3, 4))

# **kwargs untuk banyak argumen dengan nama
def Biodata(**data):
    for key, value in data.items():
        print(f"{key}: {value}")

Biodata(nama="Yasin Aprian", umur=19, kota="Batam")

"""1. **data mengumpulkan semua argumen yang dikirim dalam bentuk dictionary.
2. data.items() digunakan untuk mengakses setiap key dan value dalam dictionary tersebut.
3. print(f"{key}: {value}") akan mencetak setiap pasangan key-value dalam format <key>: <value>.

**Hands On**

Buatlah fungsi untuk mencari "***Luas Lingkaran dan Keliling Lingkaran***" dengan jari-jari 15 cm.

1. Luas Lingkaran = 3.14 * jari-jari**2
2. keliling Lingkaran = 2 * 3.14 * jari-jari
"""

# Function untuk menghitung luas lingkaran
def luas_lingkaran(jari_jari):
    luas = 3.14 * jari_jari**2
    return luas
# Function untuk menghitung keliling lingkaran
def keliling_lingkaran(jari_jari):
    keliling = 2 * 3.14 * jari_jari
    return keliling

print(luas_lingkaran(15))
print(keliling_lingkaran(15))